version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      - .:/app
    depends_on:
      - db
    command: ["./wait-for-db.sh", "db", "gunicorn", "--bind", "0.0.0.0:5000", "serve_model:app"]

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=frauddetection
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: